// ionyx-cli/src/templates/vue/frontend/App.vue
<template>
  <div class="app">
    <header class="app-header">
      <h1>{{ message }}</h1>
      
      <div v-if="appInfo" class="app-info">
        <p><strong>App:</strong> {{ appInfo.name }}</p>
        <p><strong>Version:</strong> {{ appInfo.version }}</p>
        <p><strong>Platform:</strong> {{ appInfo.platform }}</p>
      </div>
      
      <div class="features">
        <h2>🚀 Ionyx Framework Features</h2>
        <ul>
          <li>✅ File System Access</li>
          <li>✅ Network Requests</li>
          <li>✅ OS Information</li>
          <li>✅ Cross-platform Desktop Apps</li>
          <li>✅ Rust Backend Performance</li>
          <li>✅ Vue 3 Reactive Frontend</li>
        </ul>
      </div>
      
      <p>
        Edit <code>src/App.vue</code> and save to reload.
      </p>
    </header>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";

const message = ref("Loading Ionyx Framework...");
const appInfo = ref<any>(null);

onMounted(async () => {
  // Test IPC communication
  try {
    const info = await window.ionyx.invoke("app.getVersion");
    appInfo.value = info;
    message.value = "Hello from Ionyx Framework! 🚀";
  } catch (error) {
    message.value = "Error connecting to backend";
    console.error("IPC Error:", error);
  }
});
</script>

<style scoped>
.app {
  text-align: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #42b883 0%, #35495e 100%);
  color: white;
}

.app-header {
  padding: 2rem;
  max-width: 800px;
  margin: 0 auto;
}

.app-header h1 {
  font-size: 3rem;
  margin-bottom: 1rem;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
}

.app-info {
  background: rgba(255, 255, 255, 0.1);
  padding: 1.5rem;
  border-radius: 12px;
  margin: 1.5rem 0;
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.app-info p {
  margin: 0.5rem 0;
  font-size: 1.1rem;
}

.features {
  background: rgba(255, 255, 255, 0.1);
  padding: 2rem;
  border-radius: 12px;
  margin: 1.5rem 0;
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.features h2 {
  margin-bottom: 1rem;
  color: #fff;
}

.features ul {
  list-style: none;
  padding: 0;
  text-align: left;
  max-width: 400px;
  margin: 0 auto;
}

.features li {
  padding: 0.5rem 0;
  font-size: 1.1rem;
}

p {
  margin-top: 2rem;
  opacity: 0.8;
}
</style>

// ionyx-cli/my-ionyx-test/frontend/App.tsx
declare global {
  interface Window {
    ionyx: {
      invoke: (command: string, payload?: any) => Promise<any>;
    };
  }
}

import { useState, useEffect } from "react"
import "./App.css"

function App() {
  const [message, setMessage] = useState("Loading Ionyx Framework...")
  const [appInfo, setAppInfo] = useState<any>(null)

  useEffect(() => {
    // Test IPC communication
    const testIPC = async () => {
      try {
        const info = await window.ionyx.invoke("app.getVersion")
        setAppInfo(info)
        setMessage("Hello from Ionyx Framework! 🚀")
      } catch (error) {
        setMessage("Error connecting to backend")
        console.error("IPC Error:", error)
      }
    }

    testIPC()
  }, [])

  return (
    <div className="App">
      <header className="App-header">
        <h1>{message}</h1>
        {appInfo && (
          <div className="app-info">
            <p><strong>App:</strong> {appInfo.name}</p>
            <p><strong>Version:</strong> {appInfo.version}</p>
            <p><strong>Platform:</strong> {appInfo.platform}</p>
          </div>
        )}
        <div className="features">
          <h2>🚀 Ionyx Framework Features</h2>
          <ul>
            <li>✅ File System Access</li>
            <li>✅ Network Requests</li>
            <li>✅ OS Information</li>
            <li>✅ Cross-platform Desktop Apps</li>
            <li>✅ Rust Backend Performance</li>
            <li>✅ Modern Frontend Frameworks</li>
          </ul>
        </div>
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
      </header>
    </div>
  )
}

export default App
